name: PR CI - Playwright Automation

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      suite:
        description: 'Choose test suite to run'
        required: true
        default: 'sanity'
        type: choice
        options:
          - sanity
          - regression
          - all

  # Scheduled runs
  schedule:
    # Daily sanity at 2:20 PM IST → 8:50 AM UTC
    - cron: "50 8 * * *"
    # Friday regression at 6 PM IST → 12:30 PM UTC
    - cron: "30 12 * * 5"

  pull_request:
    branches:
      - main

jobs:
  sanity-job:
    if: github.event_name == 'schedule' && github.event.schedule == '50 8 * * *' || github.event_name == 'workflow_dispatch' && github.event.inputs.suite == 'sanity'
    runs-on: ubuntu-latest
    env:
      APP_USERNAME: ${{ secrets.APP_USERNAME }}
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
    defaults:
      run:
        working-directory: Automation/tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest pytest-html playwright openpyxl faker
          playwright install --with-deps chromium

      - name: Run Sanity Tests
        run: |
          pytest -v . --html=report.html --self-contained-html --maxfail=1 --disable-warnings -m sanity

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-sanity-report
          path: report.html
